services:
  nginx-web:
    image: nginx:latest
    ports:
      - "8888:80"
    depends_on:
      - fluent-bit
    command: [nginx-debug, '-g', 'daemon off;']
    # volumes:
    #  - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "false"
  apache-web:
    image: httpd
    ports:
      - "7777:80"
    depends_on:
      - fluent-bit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "false"


  fluent-bit:
    image: fluent/fluent-bit
    volumes:
        - ./fluentd/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
        - ./fluentd/parsers.conf:/fluent-bit/etc/parsers.conf
    ports:
      - "24224:24224"
      - "2020:2020"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
  
  app1:
    restart: always
    build:
      context: ./app
    expose:
      - "5000"
    environment:
      APP_NAME: "application 1"
